ktor:
  deployment:
    host: "0.0.0.0"
    port: 8080
  application:
    modules:
      - com.RoutingKt.configureRouting
koog:
  google:
    apikey: "AIzaSyDyK8HFRjfN7WISGnJHKmxD_4A3xHPQs2c"
    baseUrl: https://generativelanguage.googleapis.com

imap:
  host: "imap.gmail.com"
  port: 993
  username: "cuchopamela@gmail.com"
  password: "cpjychyqgfryjyjf"
  ssl: true
  searchDaysBack: 1
  searchDaysForward: 1
